[package]
name = "embytheater"
version = "4.0.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
hostname = "0.4"

[target.'cfg(any(target_os = "linux", target_os = "dragonfly", target_os = "freebsd", target_os = "openbsd", target_os = "netbsd"))'.dependencies]
webkit2gtk = { version = "2", features = ["v2_40"] }
gtk = "0.18"

[[bin]]
name = "embytheater"
path = "code/main.rs"

[lib]
name = "embytheater_lib"
path = "code/lib.rs"
crate-type = ["staticlib", "cdylib", "rlib"]
